create database IF NOT EXISTS libreria;

use libreria;

drop table if exists libex;

CREATE TABLE libex(
	TITULO VARCHAR(20) DEFAULT NULL,
	AUTOR VARCHAR(20) DEFAULT NULL,
	NACIONALIDAD VARCHAR(20) DEFAULT NULL,
	ID INT(4) PRIMARY KEY AUTO_INCREMENT
)ENGINE = INNODB;

ALTER TABLE `libex` DEFAULT CHARACTER SET utf16 COLLATE utf16_bin;

LOAD DATA INFILE 'C:\\wamp\\www\\jtc\\PHP\\31_biblioteca\\BIBLIOTECA.txt' INTO TABLE libex FIELDS TERMINATED BY ';'  ENCLOSED BY '"' LINES TERMINATED BY '\n';
	